services:
  worker:
    environment:
      PYTHONPATH: /app/gui
    image: geqie-app:web
    env_file:
      - .env.server
    working_dir: /app
    depends_on:
      - redis
      - db
    command: >
      sh -lc '
        set -e
        echo "===> Waiting for redis ${REDIS_HOST:-redis}:6379 ..."
        for i in $(seq 1 60); do
          (echo > /dev/tcp/${REDIS_HOST:-redis}/6379) >/dev/null 2>&1 && break
          sleep 1
        done
        echo "===> Waiting for db ${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432} ..."
        for i in $(seq 1 60); do
          (echo > /dev/tcp/${POSTGRES_HOST:-db}/${POSTGRES_PORT:-5432}) >/dev/null 2>&1 && break
          sleep 1
        done
        exec celery -A gui worker -l info -Q processing_queue
      '
    restart: unless-stopped